# рисуем закрашенные ромбы

import turtle
turtle.setup (400, 400)
turtle.fillcolor('black')
turtle.begin_fill()
turtle.left(45)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()
turtle.hideturtle()